import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
ENV_PATH = BASE_DIR / ".env"

def main():
    print("=" * 65)
    print("🚀 Telegram Custom Domain Mail Maker Bot - Setup Wizard")
    print("=" * 65)
    print("\nThis wizard will configure your bot settings and generate")
    print("exact DNS records for your domain (Namecheap / Name.com).\n")

    # 1. Bot Token
    bot_token = input("1️⃣ Enter your Telegram Bot Token (from @BotFather): ").strip()
    while not bot_token:
        bot_token = input("   ⚠️ Bot Token cannot be empty. Re-enter Token: ").strip()

    # 2. Admin ID
    admin_id = input("2️⃣ Enter your Telegram User ID (from @userinfobot): ").strip()

    # 3. Custom Domain
    domain = input("3️⃣ Enter your Custom Domain (e.g. mydomain.com): ").strip().lower()
    while not domain or "." not in domain:
        domain = input("   ⚠️ Invalid domain. Re-enter domain (e.g. mydomain.com): ").strip().lower()

    # 4. Webhook URL / Host
    webhook_host = input("4️⃣ Enter your Server IP or Public Domain (press Enter for 'localhost'): ").strip()
    if not webhook_host:
        webhook_host = "localhost"

    webhook_secret = "secret_" + os.urandom(6).hex()

    # Save to .env
    env_content = f"""# Auto-generated by Setup Wizard
BOT_TOKEN={bot_token}
ADMIN_IDS={admin_id}
DEFAULT_DOMAINS={domain}

WEBHOOK_HOST=0.0.0.0
WEBHOOK_PORT=8080
WEBHOOK_SECRET={webhook_secret}

IMAP_ENABLED=false
DATABASE_PATH=mail_bot.db
CLEANUP_INTERVAL_MINUTES=5
"""
    with open(ENV_PATH, "w", encoding="utf-8") as f:
        f.write(env_content)

    print("\n" + "✅ " * 20)
    print("Configuration saved to .env file successfully!")
    print("✅ " * 20 + "\n")

    print("=" * 65)
    print(f"📋 EXACT NAMECHEAP / NAME.COM SETUP STEPS FOR '{domain}':")
    print("=" * 65)
    print("""
METHOD A: Cloudflare Free Email Routing (RECOMMENDED & 100% FREE)
---------------------------------------------------------------
1. Log into your Namecheap account -> Domain List -> Manage.
2. Change 'Nameservers' from Namecheap BasicDNS to 'Custom DNS'.
3. Log into Cloudflare.com (Free) -> Add Site -> type your domain.
4. Copy the 2 Cloudflare Nameservers (e.g. alina.ns.cloudflare.com) and paste into Namecheap.
5. In Cloudflare Dashboard -> Email Routing -> Enable Email Routing.
6. Cloudflare will add the MX & TXT SPF records automatically!
7. Go to Cloudflare Workers -> Create Worker:
   - Copy code from: cloudflare/email_worker.js
   - Set Environment Variable in Worker Settings:
     WEBHOOK_URL = http://{webhook_host}:8080/webhook/email
     WEBHOOK_SECRET = {webhook_secret}
8. In Cloudflare Email Routing -> Catch-all Rule -> Action: Send to Worker.

METHOD B: Namecheap Built-in Email Forwarding
---------------------------------------------------------------
1. In Namecheap -> Domain List -> Manage -> Redirect Email.
2. Click 'Add Catch-All' -> Forward to your primary email or IMAP inbox.
3. Edit .env to set IMAP_ENABLED=true with your IMAP login details.
""".format(webhook_host=webhook_host, webhook_secret=webhook_secret))

    print("=" * 65)
    print("🎉 SETUP COMPLETE!")
    print("To start your bot now, run:")
    print("   python main.py")
    print("=" * 65 + "\n")

if __name__ == "__main__":
    main()
